server:
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 539421342744-jsihr232hj0e75rghuvutodiltu17e58.apps.googleusercontent.com
            client-secret: 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
  cloud:
    gateway:
      routes:
        - id: api
          uri: lb://api
          predicates:
            - Path=/api/**
        - id: replay
          uri: lb://replay
          predicates:
            - Path=/replay/**
      default-filters:
        - name: Retry
          args:
            retries: 5
            methods: GET, POST, PUT, DELETE
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
logging:
  level:
    org.springframework.security: trace